services:
- name: reaction-core-ems-pi
  root_domain: ems-test.io
  dns_name: reaction-core-pi
  desired_task_count: 1
  min_task_count: 0
  max_task_count: 2
  min_healthy_percent: 100
  max_percent: 200
  alb_listener_port: 80
  alb_listener_path: /
  alb_health_check_path: /health
  task-definition:
    name: dev-core-ems-pi
    containers:
    - name: core
      cpu: 500
      memory: 1800
      port_mappings:
      - container_port: 3000
        host_port: 3000
      image: sportsdirect/reaction
      image_tag: develop
      env_params:
      - name: CERTIFICATE_ARN
      - name: REACTION_AUTH
      - name: REACTION_EMAIL
      - name: REACTION_USER
      - name: MONGO_URL
      - name: ROOT_URL
      - name: HYDRA_ADMIN_URL
      - name: HYDRA_OAUTH2_INTROSPECT_URL
      - name: SKIP_FIXTURES
      - name: RADIAL_STORE_ID
      - name: RADIAL_API_KEY
      - name: RADIAL_MODE
